CREATE TABLE `messages` (
  `user_id` varchar(200) NOT NULL,
  `username` varchar(200) NOT NULL,
  `first_name` varchar(200) NOT NULL,
  `message_id` varchar(200) NOT NULL,
  `text` varchar(200) NOT NULL,
  `date` varchar(200) NOT NULL,
  `ndate` varchar(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
